### ISSUE TITLE
Make screen to connect points.

### ISSUE THREAD

**Issue by Leo5661** [IPV6P2P/IPV6P2PAPP#9]
## Tasks in this: 

- [ ] Search Input to enter the IPV6 address of the point to add it.
- [ ] Show the status if the address is found or not.
- [ ] If found show the Name input field for that point.
- [ ] A button with the label "Make Point" to save the point in the user connection list.

### Validation 
To enable the button to save any point are as follows.

- [ ] IPV6 address must be a valid address.
- [ ] Connection status must be successful with the new point IPV6 address.
- [ ] Name field must not be empty.
